# Generated by Django 5.0.6 on 2025-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Recieved', max_length=15),
        ),
    ]
